Feat(API): Add stripe integration and updated icon and title
Arjunmdas3211/myshop pull request #4
Opened 2020-10-06 06:24 UTC by Arjunmdas3211

2020-10-11 09:39 UTC, amouxkin requested changes

2020-10-11 09:39 UTC, amouxkin commented on src/components/stripe-button/stripe-button.component.jsx
> +    'pk_test_51HYtKcFJo0QElKHXVL5UKRL0E9YMFQhnQ6CxFLCWDKoFKGcFSZVCfJ0zNOK858XzlEa7E9dzoksV8Oeo3gshagIf00I5gKjrwk';
Try to put this in a `.env` file.

2020-10-12 06:44 UTC, Arjunmdas3211 commented on src/components/stripe-button/stripe-button.component.jsx
> +    'pk_test_51HYtKcFJo0QElKHXVL5UKRL0E9YMFQhnQ6CxFLCWDKoFKGcFSZVCfJ0zNOK858XzlEa7E9dzoksV8Oeo3gshagIf00I5gKjrwk';
yea . ok bro

2020-10-12 08:13 UTC, amouxkin approved these changes

2020-10-13 06:08 UTC, merged